version: '3.4'

services:
  company.api:
    image: companyapi:dev
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "Company.API"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_company.api$
    volumes:
      - E:\senthil\git2\e-stockmarket\E-StockMarket_BackEnd\src\Services\Company\Company.API:/app
      - E:\senthil\git2\e-stockmarket\E-StockMarket_BackEnd\src:/src
      - C:\Users\User\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_company.api$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_company.api$ \"/app/bin/Debug/net5.0/Company.API.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
  ocelotapigw:
    image: ocelotapigw:dev
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "OcelotApiGw"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_ocelotapigw$
    volumes:
      - E:\senthil\git2\e-stockmarket\E-StockMarket_BackEnd\src\ApiGateway\OcelotApiGw:/app
      - E:\senthil\git2\e-stockmarket\E-StockMarket_BackEnd\src:/src
      - C:\Users\User\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_ocelotapigw$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_ocelotapigw$ \"/app/bin/Debug/net5.0/OcelotApiGw.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true

  stock.api:
    image: stockapi:dev
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "Stock.API"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_stock.api$
    volumes:
      - E:\senthil\git2\e-stockmarket\E-StockMarket_BackEnd\src\Services\Stock:/app
      - E:\senthil\git2\e-stockmarket\E-StockMarket_BackEnd\src:/src
      - C:\Users\User\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_stock.api$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_stock.api$ \"/app/bin/Debug/net5.0/Stock.API.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
