version: '3.4'

services:
  companydb:
    image: mongo

  rabbitmq:
    image: rabbitmq:3-management-alpine

  company.api:
    image: ${DOCKER_REGISTRY-}companyapi
    build:
      context: .
      dockerfile: Services/Company/Company.API/Dockerfile

  stock.api:
    image: ${DOCKER_REGISTRY-}stockapi
    build:
      context: .
      dockerfile: Services/Stock/Dockerfile

  ocelotapigw:
    image: ${DOCKER_REGISTRY-}ocelotapigw
    build:
      context: .
      dockerfile: ApiGateway/OcelotApiGw/Dockerfile 

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2

volumes:
  mongo_data:
  elasticsearch-data:
