export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';

export const ADD_COMPANY = 'ADD_COMPANY';
export const SELECTED_COMPANY = 'SELECTED_COMPANY';
export const FETCH_COMPANY = 'FETCH_COMPANY';
export const FETCH_COMPANY_ERROR = 'FETCH_COMPANY_ERROR';
export const SET_COMPANIES = 'SET_COMPANIES';
export const LOADING_COMPANIES = 'SET_COMPANIES';
